--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/13/2022 12:44:14 AM
-- Server version: 10.4.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO kiara.comercial(IdPropiedad, Estacionamiento, Cuartos, Oficinas, Niveles) VALUES
(6, 2, 5, 1, 1),
(7, 3, 5, 1, 1),
(8, 2, 5, 2, 1),
(9, 1, 3, 3, 2),
(10, 1, 1, 5, 2),
(11, 1, 2, 7, 2),
(12, 5, 2, 10, 4);