--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/13/2022 12:44:14 AM
-- Server version: 10.4.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO kiara.propiedades(IdPropiedad, Descripcion, Precio, Estado, Municipio, Colonia, Calle, CP, `Uso de Suelo`, Terreno, Video, IMG, TipoTransaccion) VALUES
(1, 'Casa en venta', 4000000, 'Queretaro', 'Queretaro', 'Alamos', 'Circuito Alamos', 76269, 'Residencial', 162, '', '', '1'),
(2, 'Casa en venta', 3500000, 'Queretaro', 'Queretaro', 'Alamos', 'Circuito Alamos', 76269, 'Residencial', 147, '', '', '1'),
(3, 'Casa en venta', 7300000, 'Queretaro', 'Queretaro', 'Carretas', 'Circuito Alamos', 76269, 'Residencial', 190, '', '', '1'),
(4, 'Casa en venta', 7550000, 'Queretaro', 'Queretaro', 'Carretas', 'Circuito Alamos', 76269, 'Residencial', 261, '', '', '1'),
(5, 'Casa en renta', 8790000, 'Queretaro', 'Queretaro', 'Carretas', 'Circuito Alamos', 76269, 'Residencial', 164, '', '', '2'),
(6, 'Local en venta', 10030000, 'Queretaro', 'Queretaro', 'Carretas', 'Circuito Alamos', 76269, 'Comercial', 115, '', '', '1'),
(7, 'Local en venta', 11270000, 'Queretaro', 'Queretaro', 'Alamos', 'Circuito Alamos', 76269, 'Comercial', 286, '', '', '1'),
(8, 'Local en venta', 12510000, 'Queretaro', 'Queretaro', 'Alamos', 'Circuito Alamos', 76269, 'Comercial', 116, '', '', '1'),
(9, 'Local en venta', 13750000, 'Queretaro', 'El Marques', 'Zakia', 'Circuito Azaleas', 76269, 'Comercial', 219, '', '', '1'),
(10, 'Local en venta', 14990000, 'Queretaro', 'El Marques', 'Zibata', 'Circuito Azaleas', 76269, 'Comercial', 280, '', '', '2'),
(11, 'Local en venta', 16230000, 'Queretaro', 'El Marques', 'Zakia', 'Circuito Azaleas', 76269, 'Comercial', 155, '', '', '1'),
(12, 'Local en venta', 17470000, 'Queretaro', 'El Marques', 'Zakia', 'Circuito Azaleas', 76269, 'Comercial', 229, '', '', '1'),
(13, 'Departamento en venta', 18710000, 'Queretaro', 'El Marques', 'Zakia', 'Circuito Azaleas', 76269, 'Residencial', 261, '', '', '1'),
(14, 'Departamento en venta o renta', 19950000, 'Queretaro', 'El Marques', 'El Refugio', 'Circuito Azaleas', 76420, 'Residencial', 199, '', '', '3'),
(15, 'Departamento en venta', 21190000, 'Queretaro', 'El Marques', 'El Refugio', 'Circuito Azaleas', 76420, 'Residencial', 128, '', '', '1'),
(16, 'Departamento en venta', 22430000, 'Queretaro', 'El Marques', 'El Refugio', 'Circuito Azaleas', 76420, 'Residencial', 165, '', '', '1'),
(17, 'Departamento en renta', 23670000, 'Queretaro', 'El Marques', 'Zakia', 'Circuito Azaleas', 76420, 'Residencial', 102, '', '', '2'),
(18, 'Terreno', 24910000, 'Queretaro', 'El Marques', 'Zakia', 'Circuito Azaleas', 76420, 'Mixto', 275, '', '', '1'),
(19, 'Terreno', 26150000, 'Queretaro', 'El Marques', 'Zakia', 'Circuito Azaleas', 76420, 'Mixto', 177, '', '', '3'),
(20, 'Terreno', 27390000, 'Queretaro', 'El Marques', 'Zakia', 'Circuito Azaleas', 76420, 'Residencial', 292, '', '', '1'),
(21, 'Casa bonita', 5000, 'Queretaro', 'Queretaro', 'Epigmenio Gonzalez', 'Las rosas 23', 42064, 'Residencial', 120, NULL, NULL, '1'),
(22, 'Casa en renta', 3000000, 'Queretaro', 'Queretaro', 'El Refugio', 'Circuito Berengena ', 76269, 'Residencial', 216, '', '', '2\r\n2');