--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/13/2022 12:44:14 AM
-- Server version: 10.4.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO kiara.terreno(IdPropiedad, `Medida Frente`, `Medida Fondo`, `Uso de suelo`, Agua, Luz, Drenaje, Desivel, `Forma de Terreno`) VALUES
(18, 10, 10, 4, 1, 1, 1, 0, 'Cuadrado'),
(19, 10, 20, 4, 1, 0, 1, 0, 'Rectangular'),
(20, 15, 10, 1, 1, 0, 1, 0, 'Rectangular');