--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/13/2022 12:44:14 AM
-- Server version: 10.4.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO kiara.tipo_exp(Tipo_Exp, Descripion) VALUES
(1, 'Expediente Propietario'),
(2, 'Expediente Conyugue de Propietario'),
(3, 'Expediente Comprador\r\n'),
(4, 'Expediente Conyugue Comprador'),
(5, 'Expediente Solicitante Arrendamiento'),
(6, 'Expediente Obligado Solidario Arrendamiento'),
(7, 'Expediente Propietario del inmueble a arrendar');