--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/10/2022 11:01:13 PM
-- Server version: 10.4.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO kiara.asignacion(IdEmpleado, IdPropiedad, fecha_asignacion) VALUES
(2, 1, '2022-10-10 00:00:00');









INSERT INTO kiara.propiedades(IdPropiedad, Descripcion, Precio, Estado, Municipio, Colonia, Calle, CP, `Uso de Suelo`, Terreno, Video, IMG, TipoTransaccion) VALUES
(1, 'Casa bonita', 5000, 'Queretaro', 'Queretaro', 'Epigmenio Gonzalez', 'Las rosas 23', 42064, 'Comercial', 120, NULL, NULL, NULL);




INSERT INTO kiara.residencial(IdPropiedad, baños, Recamaras, Cocina, Estacionamiento, Gas, Pisos) VALUES
(1, 2, 3, 4, 4, 1, 4);







INSERT INTO kiara.usuario(IdUsuario, email, IdRol, nombre, PA, SA, eciv, ocupacion, Telefono, password) VALUES
(1, 'mm.gracia@frenesifloral.mx', 1, 'Mariamiguel', 'Gracia', 'Perez', 'En busca de Sugar', 'Millonaria en Proceso', '7714206969', 'ffff'),
(2, 'memof2000@hotmail.com', 2, 'Guillermo Fidel', 'Navarro', 'Vega', 'Soltero', 'Estudiante', '7717486945', 'ffff');