--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/12/2022 10:03:40 AM
-- Server version: 10.4.24
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO kiara.usuario(IdUsuario, email, IdRol, nombre, PA, SA, eciv, ocupacion, Telefono, password) VALUES
(1, 'Luis.Solis@hotmail.com', 2, 'Luis', 'Solis', 'Gracia', 'Soltero', 'Licenciado', '728172173', NULL),
(2, 'Guillermo.De Soto@hotmail.com', 2, 'Guillermo', 'De Soto', 'Garcia', 'Soltero', 'Licenciado', '728172174', NULL),
(3, 'Fidel.Torres@hotmail.com', 2, 'Fidel', 'Torres', 'Garza', 'Soltero', 'Licenciado', '728172175', NULL),
(4, 'David.Landa@hotmail.com', 2, 'David', 'Landa', 'Pelaes', 'Soltero', 'Licenciado', '728172176', NULL),
(5, 'Michelle.Soto@hotmail.com', 2, 'Michelle', 'Soto', 'Virgolinni', 'Soltero', 'Licenciado', '728172177', NULL),
(6, 'Hugo.Ramos@hotmail.com', 1, 'Hugo', 'Ramos', 'Palomino', 'Soltero', 'Licenciado', '728172178', NULL),
(7, 'Armando.Vazquez@hotmail.com', 1, 'Armando', 'Vazquez', 'Nava', 'Soltero', 'Licenciado', '728172179', NULL),
(8, 'Juan.Perez@hotmail.com', 1, 'Juan', 'Perez', 'Utrera', 'Soltero', 'Licenciado', '728172180', NULL),
(9, 'Erick.Chavez@hotmail.com', 1, 'Erick', 'Chavez', 'Ponce', 'Casado', 'Licenciado', '728172181', NULL),
(10, 'Andrea.Castillo@hotmail.com', 1, 'Andrea', 'Castillo', 'Schwarzenegger', 'Soltero', 'Estudiante ', '728172182', NULL),
(11, 'Gerardo.Esparza@hotmail.com', 1, 'Gerardo', 'Esparza', 'Peregrino', 'Soltero', 'Estudiante ', '728172183', NULL),
(12, 'Enrique.Enriquez@hotmail.com', 1, 'Enrique', 'Enriquez', 'Gutierrez', 'Soltero', 'Estudiante ', '728172184', NULL),
(13, 'Juan Luis.Flores@hotmail.com', 1, 'Juan Luis', 'Flores', 'Peck', 'Soltero', 'Estudiante ', '728172185', NULL),
(14, 'Nicolas.Palos@hotmail.com', 1, 'Nicolas', 'Palos', 'de La torre', 'Soltero', 'Estudiante ', '728172186', NULL),
(15, 'Fernando.Atocha@hotmail.com', 1, 'Fernando', 'Atocha', 'Hernandez', 'Soltero', 'Estudiante ', '728172187', NULL),
(16, 'Patricio.Olmo@hotmail.com', 1, 'Patricio', 'Olmo', 'Solis', 'Soltero', 'Estudiante ', '728172188', NULL),
(17, 'Antonio.Cordoba@hotmail.com', 1, 'Antonio', 'Cordoba', 'Cordoba', 'Soltero', 'Estudiante ', '728172189', NULL),
(18, 'Luperdo.Fajardo@hotmail.com', 1, 'Luperdo', 'Fajardo', 'Leon', 'Soltero', 'Estudiante ', '728172190', NULL),
(19, 'Javier.Ochoa@hotmail.com', 1, 'Javier', 'Ochoa', 'Nuñez', 'Soltero', 'Estudiante ', '728172191', NULL),
(20, 'Ivan.Gutierrez@hotmail.com', 1, 'Ivan', 'Gutierrez', 'Olmedo', 'Soltero', 'Estudiante ', '728172192', NULL),
(21, 'mm.gracia@frenesifloral.mx', 1, 'Mariamiguel', 'Gracia', 'Perez', 'Soltero', 'Estudiante', '7714206969', NULL),
(22, 'memof2000@hotmail.com', 3, 'Guillermo Fidel', 'Navarro', 'Vega', 'Soltero', 'Estudiante', '7717486945', 'ffff'),
(24, 'Daniel.Cordova@hotmail.com', 1, 'Daniel', 'Cordova', 'Perez', 'Soltero', 'Licenciado', '728172172', NULL);